### ISSUE TITLE
Auto Backups?

### ISSUE THREAD

**Issue by seathasky** [ISpaikI/Enshrouded-Server-Manager#14]
Possible to implement server saves automatically within the app?

**Comment by ISpaikI** [comment]
Could be possible, but the storage taken could be huge. You have to delete all old backups you dont want anymore manually

**Comment by ISpaikI** [comment]
Oh and for the next time, if you have an idea or a suggestion we have discussions open :)

**Comment by ISpaikI** [comment]
Thought a little bit about it. We try to not use admin settings, means asblong is is checked for auto backup it would make backups. Means if its running or not.

**Comment by seathasky** [comment]
> Could be possible, but the storage taken could be huge. You have to delete all old backups you dont want anymore manually

For instance, WindowsGSM only keeps the last 3 backups. I'm sure that could be achieved as well.

**Comment by Crazyloon** [comment]
I had written an Auto-backup script before working on this tool. Here are my thoughts.

As a user, I want an auto-backup setting that allows me to control how often backups are scheduled, and how many backups I save.

As a user, when I reach the maximum number of backups I have configured, I want the oldest backup to be deleted and replaced with the new backup.

**Comment by ISpaikI** [comment]
- Important is to check the server that is running, you should not be able to run the auto backup twice
- we could auto backup only if the file has a newer timestamp than on last check
- we could make variables for time from backup to backup and amount of max saved
- it can be started with server start, but as said... It needs to stop by process stop (need to program pid) or it should not be toggled while active

**Comment by ISpaikI** [comment]
Will come with 0.2.0

**Comment by Crazyloon** [comment]
Version 0.2.0 has been released with auto backup as the primary feature
