### ISSUE TITLE
Run as a service on system startup

### ISSUE THREAD

**Issue by brettinternet** [ISpaikI/Enshrouded-Server-Manager#26]
Hi, thank you for this very convenient app. Is there a method to start servers as a service on system startup?

**Comment by ISpaikI** [comment]
Not on the state of the app right now. Not as i know. But thats something we could look in the future into. But i cant promise on a feature like that.

**Comment by Crazyloon** [comment]
In the meantime, conside having a look at this, which may be useful http://nssm.cc/

**Comment by ISpaikI** [comment]
Would be nice to add ideas in ideas discussion section. 
So we dont forget about it.
