### ISSUE TITLE
Support more alphabets

### ISSUE THREAD

**Issue by xXFreeFunXx** [ISpaikI/Enshrouded-Server-Manager#8]
![](https://cdn.discordapp.com/attachments/1106326089569148999/1199750300278468772/Enshrouded_Server_Manager_a5dqAWuKJT.png?ex=65c3ad89&is=65b13889&hm=7a45f31bd0d6fb7af7c843d93c073790f12cce28b2f6f261136890c6d9cbeba3&)

The Latin alphabet is not used worldwide. Windows and many other applications can also handle other characters.
It is best to orientate yourself on what Windows can do.

**Comment by Crazyloon** [comment]
The primary goal behind this was to prevent any issues with windows file paths. We can make an update to allow more characters

**Comment by Crazyloon** [comment]
0.2.0 has been updated to allow all characters outside of those restricted by Windows file and path naming conventions
